[build]
  command = "npm run build --workspace redDragonStore"
  publish = "redDragonStore/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/printful/orders"
  to = "/.netlify/functions/printful-orders"
  status = 200
